#include "gba.h"
#include "apple.h"

APPLE apple;
u16 appleBitmap[13][12] = {
    {GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, BLACK, BLACK, GRASS, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, BLACK, APPLE_LIGHT_BROWN, BLACK, GRASS, GRASS, GRASS},
    {GRASS, GRASS, BLACK, BLACK, BLACK, BLACK, BLACK, APPLE_DARK_BROWN, BLACK, GRASS, GRASS, GRASS},
    {GRASS, BLACK, APPLE_DARK_GREEN, APPLE_LIGHT_GREEN, APPLE_LIGHT_GREEN, APPLE_LIGHT_GREEN, BLACK, APPLE_DARK_BROWN, BLACK, BLACK, GRASS, GRASS},
    {BLACK, APPLE_DARK_GREEN, APPLE_LIGHT_GREEN, APPLE_LIGHT_GREEN, APPLE_LIGHT_GREEN, APPLE_DARK_GREEN, BLACK, BLACK, APPLE_LIGHT_RED, APPLE_LIGHT_RED, BLACK, GRASS},
    {BLACK, APPLE_DARK_GREEN, APPLE_DARK_GREEN, APPLE_DARK_GREEN, BLACK, BLACK, APPLE_DARK_RED, APPLE_LIGHT_RED, APPLE_LIGHT_RED, APPLE_LIGHT_RED, APPLE_LIGHT_RED, BLACK},
    {BLACK, BLACK, BLACK, BLACK, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_LIGHT_RED, APPLE_LIGHT_RED, BLACK},
    {GRASS, BLACK, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_LIGHT_RED, BLACK},
    {GRASS, BLACK, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, BLACK},
    {GRASS, BLACK, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, BLACK},
    {GRASS, GRASS, BLACK, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, APPLE_DARK_RED, BLACK, GRASS},
    {GRASS, GRASS, GRASS, BLACK, APPLE_DARK_RED, APPLE_DARK_RED, BLACK, APPLE_DARK_RED, APPLE_DARK_RED, BLACK, GRASS, GRASS},
    {GRASS, GRASS, GRASS, GRASS, BLACK, BLACK, GRASS, BLACK, BLACK, GRASS, GRASS, GRASS},

};

void initializeApple()
{
  apple.y = 100;
  apple.x = 200;
  apple.height = 13;
  apple.width = 12;
  apple.bitmap = appleBitmap;
  apple.active = 1;
}

void drawApple(int x, int y, APPLE *apple_ptr)
{
  for (int i = 0; i < APPLEHEIGHT; i++)
  {
    DMANow(3, &(apple_ptr->bitmap[i * APPLEWIDTH]), &videoBuffer[OFFSET(x, y + i, SCREENWIDTH)], APPLEWIDTH);
  }
}
