#include "gba.h"
#include "flowers.h"
#include <stdio.h>
#include <stdlib.h>

FLOWER flowers[FLOWERCOUNT];
int rSeed = 0;
u16 redFlower[14][7] = {
    {GRASS, GRASS, FLOWER_LIGHT_RED, FLOWER_LIGHT_RED, FLOWER_LIGHT_RED, GRASS, GRASS},
    {GRASS, FLOWER_LIGHT_RED, FLOWER_DARK_RED, FLOWER_LIGHT_RED, FLOWER_DARK_RED, FLOWER_LIGHT_RED, GRASS},
    {GRASS, FLOWER_LIGHT_RED, FLOWER_LIGHT_RED, FLOWER_MIDDLE, FLOWER_LIGHT_RED, FLOWER_LIGHT_RED, GRASS},
    {GRASS, FLOWER_LIGHT_RED, FLOWER_DARK_RED, FLOWER_LIGHT_RED, FLOWER_DARK_RED, FLOWER_LIGHT_RED, GRASS},
    {GRASS, GRASS, FLOWER_LIGHT_RED, FLOWER_LIGHT_RED, FLOWER_LIGHT_RED, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, FLOWER_LIGHT_GREEN, FLOWER_DARK_GREEN},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, FLOWER_DARK_GREEN, GRASS},
    {FLOWER_LIGHT_GREEN, GRASS, GRASS, FLOWER_LIGHT_GREEN, FLOWER_DARK_GREEN, GRASS, GRASS},
    {GRASS, FLOWER_DARK_GREEN, FLOWER_LIGHT_GREEN, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, FLOWER_DARK_GREEN, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
};

u16 orangeFlower[14][7] = {
    {GRASS, GRASS, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, GRASS, GRASS},
    {GRASS, FLOWER_LIGHT_ORANGE, FLOWER_DARK_ORANGE, FLOWER_LIGHT_ORANGE, FLOWER_DARK_ORANGE, FLOWER_LIGHT_ORANGE, GRASS},
    {GRASS, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, FLOWER_MIDDLE, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, GRASS},
    {GRASS, FLOWER_LIGHT_ORANGE, FLOWER_DARK_ORANGE, FLOWER_LIGHT_ORANGE, FLOWER_DARK_ORANGE, FLOWER_LIGHT_ORANGE, GRASS},
    {GRASS, GRASS, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, FLOWER_LIGHT_GREEN, FLOWER_DARK_GREEN},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, FLOWER_DARK_GREEN, GRASS},
    {FLOWER_LIGHT_GREEN, GRASS, GRASS, FLOWER_LIGHT_GREEN, FLOWER_DARK_GREEN, GRASS, GRASS},
    {GRASS, FLOWER_DARK_GREEN, FLOWER_LIGHT_GREEN, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, FLOWER_DARK_GREEN, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
};

u16 purpleFlower[14][7] = {
    {GRASS, GRASS, FLOWER_LIGHT_PURPLE, FLOWER_LIGHT_PURPLE, FLOWER_LIGHT_PURPLE, GRASS, GRASS},
    {GRASS, FLOWER_LIGHT_PURPLE, FLOWER_DARK_PURPLE, FLOWER_LIGHT_PURPLE, FLOWER_DARK_PURPLE, FLOWER_LIGHT_PURPLE, GRASS},
    {GRASS, FLOWER_LIGHT_PURPLE, FLOWER_LIGHT_PURPLE, FLOWER_MIDDLE, FLOWER_LIGHT_PURPLE, FLOWER_LIGHT_PURPLE, GRASS},
    {GRASS, FLOWER_LIGHT_PURPLE, FLOWER_DARK_PURPLE, FLOWER_LIGHT_PURPLE, FLOWER_DARK_PURPLE, FLOWER_LIGHT_PURPLE, GRASS},
    {GRASS, GRASS, FLOWER_LIGHT_PURPLE, FLOWER_LIGHT_PURPLE, FLOWER_LIGHT_PURPLE, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, FLOWER_LIGHT_GREEN, FLOWER_DARK_GREEN},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, FLOWER_DARK_GREEN, GRASS},
    {FLOWER_LIGHT_GREEN, GRASS, GRASS, FLOWER_LIGHT_GREEN, FLOWER_DARK_GREEN, GRASS, GRASS},
    {GRASS, FLOWER_DARK_GREEN, FLOWER_LIGHT_GREEN, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, FLOWER_DARK_GREEN, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
};

u16 pinkFlower[14][7] = {
    {GRASS, GRASS, FLOWER_LIGHT_PINK, FLOWER_LIGHT_PINK, FLOWER_LIGHT_PINK, GRASS, GRASS},
    {GRASS, FLOWER_LIGHT_PINK, FLOWER_DARK_PINK, FLOWER_LIGHT_PINK, FLOWER_DARK_PINK, FLOWER_LIGHT_PINK, GRASS},
    {GRASS, FLOWER_LIGHT_PINK, FLOWER_LIGHT_PINK, FLOWER_MIDDLE, FLOWER_LIGHT_PINK, FLOWER_LIGHT_PINK, GRASS},
    {GRASS, FLOWER_LIGHT_PINK, FLOWER_DARK_PINK, FLOWER_LIGHT_PINK, FLOWER_DARK_PINK, FLOWER_LIGHT_PINK, GRASS},
    {GRASS, GRASS, FLOWER_LIGHT_PINK, FLOWER_LIGHT_PINK, FLOWER_LIGHT_PINK, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, FLOWER_LIGHT_GREEN, FLOWER_DARK_GREEN},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, FLOWER_DARK_GREEN, GRASS},
    {FLOWER_LIGHT_GREEN, GRASS, GRASS, FLOWER_LIGHT_GREEN, FLOWER_DARK_GREEN, GRASS, GRASS},
    {GRASS, FLOWER_DARK_GREEN, FLOWER_LIGHT_GREEN, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, FLOWER_DARK_GREEN, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
};

u16 blueFlower[14][7] = {
    {GRASS, GRASS, FLOWER_LIGHT_BLUE, FLOWER_LIGHT_BLUE, FLOWER_LIGHT_BLUE, GRASS, GRASS},
    {GRASS, FLOWER_LIGHT_BLUE, FLOWER_DARK_BLUE, FLOWER_LIGHT_BLUE, FLOWER_DARK_BLUE, FLOWER_LIGHT_BLUE, GRASS},
    {GRASS, FLOWER_LIGHT_BLUE, FLOWER_LIGHT_BLUE, FLOWER_MIDDLE, FLOWER_LIGHT_BLUE, FLOWER_LIGHT_BLUE, GRASS},
    {GRASS, FLOWER_LIGHT_BLUE, FLOWER_DARK_BLUE, FLOWER_LIGHT_BLUE, FLOWER_DARK_BLUE, FLOWER_LIGHT_BLUE, GRASS},
    {GRASS, GRASS, FLOWER_LIGHT_BLUE, FLOWER_LIGHT_BLUE, FLOWER_LIGHT_BLUE, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, FLOWER_LIGHT_GREEN, FLOWER_DARK_GREEN},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, FLOWER_DARK_GREEN, GRASS},
    {FLOWER_LIGHT_GREEN, GRASS, GRASS, FLOWER_LIGHT_GREEN, FLOWER_DARK_GREEN, GRASS, GRASS},
    {GRASS, FLOWER_DARK_GREEN, FLOWER_LIGHT_GREEN, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, FLOWER_DARK_GREEN, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, FLOWER_LIGHT_GREEN, GRASS, GRASS, GRASS},
};

u16 *flowerBitmaps[] = {redFlower, orangeFlower, purpleFlower, blueFlower, pinkFlower};

void initializeFlowers()
{
  srand(rSeed);
  for (int i = 0; i < FLOWERCOUNT; i++)
  {
    flowers[i].x = rand() % 233;
    flowers[i].y = 20 + (rand() % 126);
    flowers[i].oldx = flowers[i].x;
    flowers[i].oldy = flowers[i].y;
    flowers[i].bitmap = flowerBitmaps[i];
    if (i % 2 == 0)
    {
      flowers[i].active = 1;
    }
    else
    {
      flowers[i].active = 0;
    }
  }
  rSeed++;
}

void drawFlower(int x, int y, FLOWER *flower_ptr)
{
  for (int i = 0; i < FLOWERHEIGHT; i++)
  {
    DMANow(3, &(flower_ptr->bitmap[i * FLOWERWIDTH]), &videoBuffer[OFFSET(x, y + i, SCREENWIDTH)], FLOWERWIDTH);
  }
}