#include "gba.h"
#include "player.h"

PLAYER player;
u16 playerBitmap[16][14] = {
    {GRASS, GRASS, GRASS, GRASS, GRASS, BLACK, BLACK, BLACK, BLACK, GRASS, GRASS, GRASS, GRASS, GRASS},
    {GRASS, GRASS, GRASS, BLACK, BLACK, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, BLACK, BLACK, GRASS, GRASS, GRASS},
    {GRASS, GRASS, BLACK, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, BLACK, GRASS, GRASS},
    {GRASS, BLACK, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, FLOWER_LIGHT_ORANGE, BLACK, GRASS},
    {GRASS, BLACK, FLOWER_LIGHT_ORANGE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, FLOWER_LIGHT_ORANGE, BLACK, GRASS},
    {GRASS, BLACK, BLACK, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, BLACK, GRASS},
    {GRASS, BLACK, PINK_SKIN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, PINK_SKIN, BLACK, GRASS},
    {GRASS, BLACK, SKIN, PINK_SKIN, SKIN, BLACK, PINK_SKIN, PINK_SKIN, BLACK, SKIN, PINK_SKIN, SKIN, BLACK, GRASS},
    {GRASS, GRASS, BLACK, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, BLACK, GRASS, GRASS},
    {GRASS, BLACK, BACKPACK_GREEN, BLACK, SKIN, SKIN, BLACK, BLACK, SKIN, SKIN, BLACK, BACKPACK_GREEN, BLACK, GRASS},
    {BLACK, SKIN, BACKPACK_GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BACKPACK_GREEN, SKIN, BLACK},
    {BLACK, SKIN, BLACK, BLACK, PORTAGE, PORTAGE, WHITE, WHITE, PORTAGE, PORTAGE, BLACK, BLACK, SKIN, BLACK},
    {GRASS, BLACK, BLACK, PORTAGE, PORTAGE, PORTAGE, WHITE, WHITE, PORTAGE, PORTAGE, PORTAGE, BLACK, BLACK, GRASS},
    {GRASS, GRASS, BLACK, BLACK, BLACK, BLACK, WHITE, WHITE, BLACK, BLACK, BLACK, BLACK, GRASS, GRASS},
    {GRASS, GRASS, BLACK, BLACK, SHOE_DARKGRAY, SHOE_LIGHTGRAY, BLACK, BLACK, SHOE_LIGHTGRAY, SHOE_DARKGRAY, BLACK, BLACK, GRASS, GRASS},
    {GRASS, GRASS, GRASS, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GRASS, GRASS, GRASS},
};

void initializePlayer()
{
  player.y = 72;
  player.x = 10;
  player.oldy = player.y;
  player.oldx = player.x;
  player.xVelocity = 0;
  player.yVelocity = 0;
  player.height = 16;
  player.width = 14;
  player.bitmap = playerBitmap;
}

void drawPlayer(int x, int y, PLAYER *player_ptr)
{
  for (int i = 0; i < PLAYERHEIGHT; i++)
  {
    DMANow(3, &(player_ptr->bitmap[i * PLAYERWIDTH]), &videoBuffer[OFFSET(x, y + i, SCREENWIDTH)], PLAYERWIDTH);
  }
}
